### ISSUE TITLE
Resolver fails after enabling databases

### ISSUE THREAD

**Issue by bill-long** [microsoft/EventLogExpert#186]
After enabling several databases that were disabled, and then answering Yes to the prompt to reload all open logs, the resolver died:

```powershell
2023-06-05T15:50:30.1741003-05:00 31 EventProviderDatabaseEventResolver was instantiated at:
   at System.Environment.get_StackTrace()
   at EventLogExpert.Library.EventResolvers.EventProviderDatabaseEventResolver..ctor(IDatabaseCollectionProvider dbCollection, Action`1 tracer)
   at EventLogExpert.Library.EventResolvers.VersatileEventResolver..ctor(IDatabaseCollectionProvider dbCollection, ITraceLogger tracer)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EventLogExpert.Store.EventLog.EventLogEffects.<>c__DisplayClass4_0.<HandleOpenLogAction>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-06-05T15:50:30.1742317-05:00 31 LoadDatabases was called with 5 databasePaths.
2023-06-05T15:50:30.1742703-05:00 31   C:\Users\bilong\AppData\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases\Exchange 2019.db
2023-06-05T15:50:30.1742883-05:00 31   C:\Users\bilong\AppData\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases\Exchange 2016.db
2023-06-05T15:50:30.1743058-05:00 31   C:\Users\bilong\AppData\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases\Windows 2019.db
2023-06-05T15:50:30.1743414-05:00 31   C:\Users\bilong\AppData\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases\Windows 2016.db
2023-06-05T15:50:30.1743685-05:00 31   C:\Users\bilong\AppData\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases\Windows 2012R2.db
2023-06-05T15:50:30.2102690-05:00 29 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
2023-06-05T15:50:30.2105793-05:00 30 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
2023-06-05T15:50:30.2108675-05:00 31 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
2023-06-05T15:50:30.2111004-05:00 16 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
2023-06-05T15:50:30.2127126-05:00 31 Action: EventLogExpert.Store.StatusBar.StatusBarAction+SetResolverStatus {"ResolverStatus":"System.Func\u00601[System.Type]: Could not load file or assembly \u0027Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60\u0027. The system cannot find the file specified."}
2023-06-05T15:50:30.2140250-05:00 16 Action: EventLogExpert.Store.StatusBar.StatusBarAction+SetResolverStatus {"ResolverStatus":"System.Func\u00601[System.Type]: Could not load file or assembly \u0027Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60\u0027. The system cannot find the file specified."}
2023-06-05T15:50:30.2143968-05:00 29 Action: EventLogExpert.Store.StatusBar.StatusBarAction+SetResolverStatus {"ResolverStatus":"System.Func\u00601[System.Type]: Could not load file or assembly \u0027Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60\u0027. The system cannot find the file specified."}
2023-06-05T15:50:30.2147511-05:00 30 Action: EventLogExpert.Store.StatusBar.StatusBarAction+SetResolverStatus {"ResolverStatus":"System.Func\u00601[System.Type]: Could not load file or assembly \u0027Microsoft.Extensions.Caching.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60\u0027. The system cannot find the file specified."}

```

**Comment by bill-long** [comment]
I can't repro. The file is present in the same folder with the exe. Leaving this open for now to see if it happens again.

**Comment by bill-long** [comment]
This may have been caused by #190. I was able to reproduce various FileNotFound errors if I typed an Advanced Filter fast enough after opening the app.
