### ISSUE TITLE
Crash after setting an advanced filter and then trying to add a dropdown filter

### ISSUE THREAD

**Issue by bill-long** [microsoft/EventLogExpert#187]
```powershell
2023-06-05T16:10:33.4789364-05:00 1 Action: EventLogExpert.Store.FilterPane.FilterPaneAction+AddFilter {"FilterModel":null}
2023-06-05T16:10:33.4965706-05:00 1 Action: EventLogExpert.Store.EventLog.EventLogAction+SetFilters {"EventFilter":{"AdvancedFilter":"Description.Contains(\u0022TransportVersioned\u0022) || Description.Contains(\u0022EseNtOutOfSessions\u0022, StringComparison.OrdinalIgnoreCase)","DateFilter":null,"Filters":[{"Id":"245de447-8030-405d-a842-c7397206470a","Comparison":[],"ComparisonString":null,"IsEditing":true,"IsEnabled":true,"FilterType":0,"FilterComparison":0,"FilterValue":"","SubFilters":[]}]}}
2023-06-05T16:10:33.4966666-05:00 1 GetFilteredEvents was called to filter 385486 events.
2023-06-05T16:10:33.4980769-05:00 1 SortOneLog was called.
2023-06-05T16:10:33.7700342-05:00 1 GetFilteredEvents was called to filter 398375 events.
2023-06-05T16:10:33.7703994-05:00 1 SortOneLog was called.
2023-06-05T16:10:34.0322677-05:00 1 GetFilteredEvents was called to filter 403932 events.
2023-06-05T16:10:34.0327245-05:00 1 SortOneLog was called.
2023-06-05T16:10:34.2853774-05:00 1 GetFilteredEvents was called to filter 405302 events.
2023-06-05T16:10:34.2857268-05:00 1 SortOneLog was called.
2023-06-05T16:10:34.5453700-05:00 1 CombineLogs was called for 4 logs.
2023-06-05T16:10:34.5560410-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5684069-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5700808-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5703446-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5729921-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5732147-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
2023-06-05T16:10:34.5745583-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-06-05T16:10:34.5749973-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-06-05T16:10:34.5758863-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-06-05T16:10:34.5760878-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-06-05T16:10:34.5771637-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-06-05T16:10:34.5773795-05:00 1 System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EventLogExpert.Library.Helpers.ExtensionMethods.ToFullString(Enum value)
   at EventLogExpert.Shared.Components.FilterSelect`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by bill-long** [comment]
I can't repro this one either, and it's another FileNotFoundException for a file that is clearly present. I beginning to wonder if these were caused by an AV scan or something.

**Comment by bill-long** [comment]
Closing this and #186 for now. Still no repro. Pretty sure this was AV.

**Comment by bill-long** [comment]
This may have been caused by #190. I was able to reproduce various FileNotFound errors if I typed an Advanced Filter fast enough after opening the app.
